settings:
  title: 'Status Page'
  url: 'https://status.vpsnode.org' # used for Slack messages
  logo: 'https://cdn.discordapp.com/icons/894660129935491123/3168de2d150850253c47e4853d85044d.png' # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: site # unique identifier
    name: Website
    description: 'Our main website' # default=empty
    url: 'https://vpsnode.org/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: panel
    name: 'Control Panel'
    description: 'The server management panel'
    url: 'https://panel.vpsnode.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
  
  - id: clients
    name: 'Clients Panel'
    description: 'The server management panel'
    url: 'https://clients.vpsnode.org'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
  
  - id: node1
    name: 'Node 1'
    url: 'https://node1.vpsnode.org:8080/api/servers'
    method: GET
    expectStatus: 401
    linkable: false # allows the title to be a link, default=true
  
  - id: node1
    name: 'Node 2'
    url: 'https://node2.vpsnode.org:8080/api/servers'
    method: GET
    expectStatus: 401
    linkable: false # allows the title to be a link, default=true
